import pyrate
import sys

HELPSTRING = """pyrate is a tool for integrating S-factor data generated by AZURE into a reaction rate
pyrate requires a configuration file (JSON format) that contains the relevant reaction information (see README)
To run:
    python main.py <your_config_file>
To print this message:
    python main.py --help
"""

def main(configfile: str):
    config = pyrate.read_config_file(configfile)
    if config is None:
        print(f"Could not read configuration in file {configfile}!")
        return
    
    pyrate.calc_rate_sfactor(config)
    #pyrate.calc_rate_cross(config)

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(HELPSTRING)
    elif sys.argv[1] == "--help":
        print(HELPSTRING)
    else:
        main(sys.argv[1])